FROM golang as builder

RUN apt-get update && \
    apt-get install -y apache2-utils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download 

COPY . .

CMD ["go", "run", "cmd/main.go"]
